### ISSUE TITLE
Error hitbox arropea pegada en muro

### ISSUE THREAD

**Issue by Vicnuel5** [Proyectos1-FDI-UCM/c2021-Grupo04#1]
Descripción:

Cuando dejas la arropea pegada en una pared, a veces la hitbox de esta desaparece y no puedes subirte en ella.

Pasos:

1- Poner la arropea en tus manos (con espacio).
2- Cerca de un muro saltar y lanzar la arropea con Ctr.
3- Ahora cuando saltes la hitbox  de la bola ha desaparecido y podrás la atravesar.

He intentado esto reiteradas veces, pero no he llegado al núcleo de por qué pasa, pero sí que hay un caso en el que esto pasa siempre:

1- Poner la arropea en tus manos (con espacio).
2- Ponerte a melée de un muro.
3- Saltar y luego lanzar la arropea a la vez que se camina en la dirección del muro.
4- Si se ha llevado a cabo el error satisfactoriamente, en el momento en el que estás en el aire deberías haber atravesado la arropea.
5- Cuando vuelvas al suelo e intentes saltar hacia la arropea también la atravesarás.

De todas formas, puedes no seguir estrictamente estos últimos pasos y la arropea seguirá dando errores en ciertas ocasiones.

Captura de pantalla o vídeo:
![1](https://user-images.githubusercontent.com/81177633/119325136-e04e5d80-bc80-11eb-830a-8a717ef17f52.png)
https://youtu.be/Ka7_QaZUpes

**Comment by miggon23** [comment]
Es cierto que a veces pasa, hemos intentado asegurarnos varias veces de que se queda clavada por código, haciendo varias comprobaciones, no obstante sigue fallando, seguiremos trabajando para arreglarlo

**Comment by miggon23** [comment]
Ya hemos conseguido arreglar ese fallo!!

Era un error complicado de solucionar ya que solo nos sucedía en la build, por lo que costaba identificar el origen del problema. Actualmente hemos estado haciendo un montón de pruebas y no nos ha vuelto a pasar, así que lo damos por cerrado
