### ISSUE TITLE
No hay un segundo preso en la zona izquierda del nivel

### ISSUE THREAD

**Issue by PaulaMorillasAlonso** [Proyectos1-FDI-UCM/c2021-Grupo04#10]
Descripción:
En el paso número 6 de la prueba 2.1 se describe que debes atacar al segundo preso del nivel por la espalda y esperar a que este te detecte y comience a perseguirte, sin embargo después de vencer al primer preso, por más que continúes hacia la izuierda no encontrarás a ninguno más, sino un muro que evita que sigas avanzando.

Pasos:
Paso 1: Tras vencer al primer preso continuar hacia la izquierda.
Paso 2: Comprobar que llegas hasta un muro alto de color morado sin haber encontrado otro enemigo.

Vídeo:

https://user-images.githubusercontent.com/82317485/119361016-7dbe8700-bcab-11eb-81b7-fefea30af8a7.mp4

**Comment by miggon23** [comment]
Otro error nuestro a la hora de transcribir el plan de pruebas. Pretendíamos que el paso 6 se realizase volviendo cargar la Testing Zone 2 de nuevo
