### ISSUE TITLE
Si el antidisturbios te deja sin vida , no mueres

### ISSUE THREAD

**Issue by PaulaMorillasAlonso** [Proyectos1-FDI-UCM/c2021-Grupo04#11]
Descripción:
En relación con el error reportado anteriormente en “El antidisturbios desaparece y reaparece tras matarlo”, he descubierto que cuando está en ese modo de desaparecer y reaparecer, si te deja sin vidas no mueres y puedes seguir jugando, cuando en teoría deberías ser devuelto al menú principal.

Pasos:
Paso 1: Acércate al enemigo SWAT y asegúrate de que lleve su escudo.
Paso 2: Cuando estés lo suficientemente cerca y se gire para cargar contra ti, lanza la herropea hacia su escudo.  
Paso 3: Cuando esté apareciendo y desapareciendo, deja que te quite todas las vidas. Verás que en la interfaz no se muestra ningún corazón, pero puedes seguir jugando.

Link al video:
https://youtu.be/4Q1gR2XnApA

**Comment by miggon23** [comment]
El vídeo es privado, no podemos acceder a él

**Comment by admont02** [comment]
solucionado, gracias.
