### ISSUE TITLE
Herropea enganchada en el suelo

### ISSUE THREAD

**Issue by PaulaMorillasAlonso** [Proyectos1-FDI-UCM/c2021-Grupo04#13]
Descripción:
Generalmente cuando caminas con la herropea siguiéndote, se espera que vaya detrás tuyo en todo momento, pero ocasionalmente se queda enganchada en el suelo y no se puede continuar caminando si no se salta antes para desengancharla del suelo.

Pasos
Paso 1: Ve caminando con la herropea en el suelo, siguiéndote.
Paso 2: Ocasionalmente verás que se puede quedar enganchada en suelo, por ejemplo al ir a bajar un bordillo.

Link al vídeo:
https://youtu.be/r3ZplumgRgA

**Comment by admont02** [comment]
Esto está hecho intencionadamente para que se recoja la herropea, gracias.
