### ISSUE TITLE
El jugador se mueve cuando debería quedarse quieto

### ISSUE THREAD

**Issue by Vicnuel5** [Proyectos1-FDI-UCM/c2021-Grupo04#2]
Descripción:

Cuando dejas la arropea pegada en una pared para subirse a un terreno más elevado, y este camina, el movimiento de este no es bloqueado y se lleva la arropea consigo.

Pasos:

1- Coger la arropea con las manos.
2- Saltar y dejarla pegada a un muro.
3- Una vez la arropea pegada y tu en el suelo, saltar manteniendo el botón pulsado haciendo una especie de “doble salto” (el jugo tiene un efecto de sonido especial fácilmente identificable) llegando a saltar la pared.
4- Continuar tu camino sin recoger la arropea.
5- La arropea se debería mover contigo pero esta estará “hundida en el suelo”, por lo que el jugador no podrá verla. El jugador se moverá más lento en vez de bloquearse que es lo que debería pasar.

Captura de pantalla o vídeo:
![Sin título](https://user-images.githubusercontent.com/81177633/119325877-a6318b80-bc81-11eb-9286-5d9ed775f9c3.png)

**Comment by admont02** [comment]
Como te he dicho en el otro issue, la HERROPEA(no "arropea") está detrás del tilemap, recógela, no es un error, el juego es así!!!
