### ISSUE TITLE
La arropea desaparece

### ISSUE THREAD

**Issue by Vicnuel5** [Proyectos1-FDI-UCM/c2021-Grupo04#3]
Descripción:

Cuando dejas la arropea en una una plataforma de latitud inferior a la que se encuentra el jugador y saltas, esta desaparece. 

Pasos:

1- Irte a un sitio en el que hay una elevación del terreno
2- Caminar normalmente arrastrando la arropea
3- Cuando llegues a la pequeña elevación saltar y seguir caminado hasta dejar encallada la arropea
4- Una encallada, saltar
5- Se podrá apreciar como la arropea se ha hundido en el suelo, desapareciendo de su sitio anterior  y te verás ralentizado como si la llevaras arrastrando

Captura de pantalla o vídeo:
![3](https://user-images.githubusercontent.com/81177633/119326245-fad50680-bc81-11eb-8a7f-3cbb6710f5ec.png)
![4](https://user-images.githubusercontent.com/81177633/119326299-09bbb900-bc82-11eb-92b6-e16cdaad582b.png)
https://youtu.be/7AB7Hy-3B_I

**Comment by admont02** [comment]
Esto no es un error, la HERROPEA (no "arropea"), simplemente pasa por detrás de la capa del Tilemap, si la recoges no tendrás ningún tipo de problema, ni se ha vuelto invisible ni ha desaparecido.
