### ISSUE TITLE
Fantasma antidisturbio

### ISSUE THREAD

**Issue by Mennggen** [Proyectos1-FDI-UCM/c2021-Grupo04#4]
**Descripción**
Al matar el antidisturbio con una forma rara, se convierte en un fantasma que aparece y desaparece y te ataca.
**Pasos**

1. Iniciar el juego con la escena “Testing zone 2”.
2. Camina hacia la derecha para encontrar a un antidisturbio.
3. Dejar la bola en su pie cuando está cargando el escudo.
4. Cuando deja de cargar y te ataca, se moriría al colisionar con la bola.
5. Desde allí empieza a aparecer y desaparecer.

**Captura de pantalla o vídeo**
Enlace del video: https://youtu.be/4fsvFmHWB20

**Comment by admont02** [comment]
Solucionado, gracias.
