### ISSUE TITLE
Subir hasta el infinito

### ISSUE THREAD

**Issue by Vicnuel5** [Proyectos1-FDI-UCM/c2021-Grupo04#5]
Descripción:

La dejar encallada la arropea a una pared, si recoges la arropea puedes subir alturas que deberían ser inalcanzables.

Pasos:

1- Irte a un sitio en el que haya una pared.
2- Saltar y lanzar la bola para pegarla contra el muro.
3- Subirte a la bola.
4- Una vez encima, pulsar espacio para recoger la bola.
5- Se podrá ver al jugador rompiendo las leyes de la física y subiendo con la bola mientras la va recogiendo.

Captura de pantalla o vídeo:
![5](https://user-images.githubusercontent.com/81177633/119327120-ec3b1f00-bc82-11eb-9257-72116cf082c0.png)
![6](https://user-images.githubusercontent.com/81177633/119327157-f65d1d80-bc82-11eb-8845-e954b65156db.png)
https://youtu.be/_Gg8Nj9UA-Q

**Comment by admont02** [comment]
Ya lo hemos solucionado, muchas gracias.
