### ISSUE TITLE
La cama mágica

### ISSUE THREAD

**Issue by Mennggen** [Proyectos1-FDI-UCM/c2021-Grupo04#6]
**Descripción**
La cama en principio es blanco pero el jugador al pasar por la cama, se cambia el color.
**Pasos**

1. Inicia el juego con cualquier escena.
2. Pasar por al lado de la cama.

**Captura de pantalla o vídeo**
![微信截图_20210523234728](https://user-images.githubusercontent.com/81177341/119327252-1096fb80-bc83-11eb-87d2-ea09bc8e940a.png)
![微信截图_20210523234742](https://user-images.githubusercontent.com/81177341/119327268-14c31900-bc83-11eb-82c6-73f1e0d28ad7.png)

**Comment by admont02** [comment]
> **Descripción**
> La cama en principio es blanco pero el jugador al pasar por la cama, se cambia el color.
> **Pasos**
> 
> 1. Inicia el juego con cualquier escena.
> 2. Pasar por al lado de la cama.
> 
> **Captura de pantalla o vídeo**
> ![微信截图_20210523234728](https://user-images.githubusercontent.com/81177341/119327252-1096fb80-bc83-11eb-87d2-ea09bc8e940a.png)
> ![微信截图_20210523234742](https://user-images.githubusercontent.com/81177341/119327268-14c31900-bc83-11eb-82c6-73f1e0d28ad7.png)

La cama se pone amarilla cuando pasas por ella y se activa el checkpoint, no es "mágica"....

**Comment by miggon23** [comment]
Exacto, el cambio de color es para indicar que acabas de pasar por el checkpoint, no estaba especificado que cambiase de color la cama porque no entraba dentro de nuestro plan de pruebas.

**Comment by miggon23** [comment]
Exacto, el cambio de color es para indicar que acabas de pasar por el checkpoint, no estaba especificado que cambiase de color la cama porque no entraba dentro de nuestro plan de pruebas.
