### ISSUE TITLE
Antidisturbios está en segunda escena

### ISSUE THREAD

**Issue by Mennggen** [Proyectos1-FDI-UCM/c2021-Grupo04#7]
**Descripción**
Según el plan de pruebas, el antidisturbio se encuentra en la escena de prueba 1 pero eso no es cierto.
**Pasos**
Iniciar el juego con la escena “Testing zone 1” .

1. Camina hacia la derecha y nos damos cuenta de que no existe antidisturbio.
2. Cambiamos al escena “Testing zone 2”.
3. Caminamos hacia la derecha y encontramos el antidisturbio.

**Captura de pantalla o vídeo**
![微信截图_20210524001542](https://user-images.githubusercontent.com/81177341/119327451-49cf6b80-bc83-11eb-8053-de077aae9e1a.png)
![微信截图_20210524001601](https://user-images.githubusercontent.com/81177341/119327460-4b992f00-bc83-11eb-92a5-62a3995b0597.png)

**Comment by miggon23** [comment]
Eso es debido a un fallo nuestro al transcribir el plan pruebas, sin duda queríamos referirnos a la Testing Zone 2.
