### ISSUE TITLE
El jugador no inicia junto con la cama

### ISSUE THREAD

**Issue by Mennggen** [Proyectos1-FDI-UCM/c2021-Grupo04#8]
**Descripción**
Según el plan de prueba, deberíamos inicial el juego con el jugador junto a la cama, pero no ocurrió. Luego he seguido la solución del plan de prueba para resolver ese bug, pero no es 100% funciona.
**Pasos**

1. Detallar los pasos seguidos para poder reproducir el error. Si no se ha podido reproducir, entonces indicarlo igualmente.
2. Pulsar “Select zone”.
3. Pulsar “Testing zone 1”.
4. Pulsar escape.
5. Pulsar “Exit game” y aceptar.
6. Volver a pulsar “Select Zone” y esta vez ir a “Testing zone 2”.
7. Camina un poco y vuelve con escape y entra en “Testing zone 1”.

**Captura de pantalla o vídeo**
![微信截图_20210523234728](https://user-images.githubusercontent.com/81177341/119327664-81d6ae80-bc83-11eb-95d7-329215cade98.png)

**Comment by miggon23** [comment]
Eso es correcto, lo de iniciar junto a la cama era para saber que estás bien posicionado. Cuando cargas la misma escena que el último colchón que visitaste, aparecerás en el colchón, pero si cambias de escena, aparecerás en la zona de spawn, no en el checkpoint directamente
